#!/usr/bin/env python3
"""Update signing for «مربع چت» (Windows).

  sign.py pub  KEY.pem OUT.h     → the public key as a C BCRYPT_ECCPUBLIC_BLOB (built into the program)
  sign.py sign KEY.pem FILE OUT  → ECDSA P-256 / SHA-256 signature of FILE as hex r||s (what BCryptVerifySignature takes)

The private key (update-key.pem) never ships: apps/ is left out of the plugin zip, so a hacked site cannot sign
a program that installed copies would accept. Keep it (and this repository) private; a new key means installed
copies refuse updates until they are reinstalled by hand.
"""
import subprocess, sys

def run(*a, data=None):
    return subprocess.run(a, input=data, check=True, capture_output=True).stdout

def der_ints(der):
    # SEQUENCE { INTEGER r, INTEGER s }
    assert der[0] == 0x30
    i = 2 if der[1] < 0x80 else 2 + (der[1] & 0x7f)
    out = []
    for _ in range(2):
        assert der[i] == 0x02
        n = der[i + 1]
        v = der[i + 2:i + 2 + n]
        out.append(int.from_bytes(v, 'big'))
        i += 2 + n
    return out

if sys.argv[1] == 'pub':
    pub = run('openssl', 'ec', '-in', sys.argv[2], '-pubout', '-outform', 'DER')
    xy = pub[-64:]  # uncompressed point 04 || X || Y at the end of the SubjectPublicKeyInfo
    assert pub[-65] == 4
    blob = b'ECS1' + (32).to_bytes(4, 'little') + xy  # BCRYPT_ECDSA_PUBLIC_P256_MAGIC, cbKey
    with open(sys.argv[3], 'w') as f:
        f.write('/* generated by sign.py pub: the key that update downloads must be signed with */\n')
        f.write('static const unsigned char UPDATE_KEY[%d] = { %s };\n' % (len(blob), ', '.join('0x%02x' % b for b in blob)))
elif sys.argv[1] == 'sign':
    der = run('openssl', 'dgst', '-sha256', '-sign', sys.argv[2], sys.argv[3])
    r, s = der_ints(der)
    raw = r.to_bytes(32, 'big') + s.to_bytes(32, 'big')
    with open(sys.argv[4], 'w') as f:
        f.write(raw.hex() + '\n')
